name: Run Go Script
on:
    workflow_dispatch: {}
    schedule:
        - cron: '0 15 * * *'

jobs:
    run-go-script:
        runs-on: [self-hosted, Windows, X64]

        steps:
          - name: Run Go script
            run: |
                cd ../../../Workers/SchedulerBot
                git pull https://github.com/YoshidaTools/SchedulerDiscordBot.git
                go mod tidy
                go run main.go